### ISSUE TITLE
Get the current device, in a static way

### ISSUE THREAD

**Issue by phimage** [devicekit/DeviceKit#130]
I am wondering if there is any reason why there is no shared instance, like `UIDevice` could have one named `current`

Could I PR this? (or you can add it)

```swift
extension Device {
    /// Return the current device instance.
    public static let current = Device()
}
```

ps: `static` variable seems to be lazy loaded.

**Comment by dennisweissmann** [comment]
You're right, the device the code runs on never changes, right? I'd leave it open and put it as a breaking change in the major next release (together with removing the `init`? Or is there a use-case where one would need to instantiate the exact same again and again?)

**Comment by narek-sv** [comment]
in that case he do something like this
`let copy = Device.current`
