### ISSUE TITLE
Feature request: Add allWithRoundedCorners

### ISSUE THREAD

**Issue by salvasp** [devicekit/DeviceKit#159]
It would be useful a category that contains all the models with the screen with rounded edges

For now should contain [.iPhoneX, .iPhoneXs, .iPhoneXsMax, .iPhoneXr, .iPadPro12Inch3] If I'm not mistaken

and also Device().[hasRoundCorners / roundCorners] (true/false or radius size)

ps .allXSeriesDevices should be renamed to .allXSeries for consistency
also allPlusSizedDevices, allProDevices and so on

**Comment by dennisweissmann** [comment]
Good points, I will take them into account for version 2.0 of the framework :)
