### ISSUE TITLE
[BUG] Using UIDevice.current on isPhone and isPad variables.

### ISSUE THREAD

**Issue by Zandor300** [devicekit/DeviceKit#165]
If you see the following lines:

https://github.com/dennisweissmann/DeviceKit/blob/master/Source/Device.generated.swift#L584
https://github.com/dennisweissmann/DeviceKit/blob/master/Source/Device.generated.swift#L591

```swift
/// Returns whether the device is an iPhone (real or simulator)
public var isPhone: Bool {
  return (isOneOf(Device.allPhones)
          || isOneOf(Device.allSimulatorPhones)
          || UIDevice.current.userInterfaceIdiom == .phone) && !isPod
}

/// Returns whether the device is an iPad (real or simulator)
public var isPad: Bool {
  return isOneOf(Device.allPads)
          || isOneOf(Device.allSimulatorPads)
          || UIDevice.current.userInterfaceIdiom == .pad
}
```

`UIDevice.current` is used.

Imagine this example; I'm running on an iPhone X. I'm getting an instance of `.iPad6` and checking for `.isPhone` on that instance. From my understanding, it would return `true` since `(UIDevice.current.userInterfaceIdiom == .phone) == true`.

Do note that I haven't tested this.

@dennisweissmann mentioning you since you like that so much 😉 and because I can't assign you.

**Comment by Zandor300** [comment]
Just confirmed this:

```swift
print(Device().description)
        
let ipad = Device.iPad6
print(ipad.isPhone)
```

Output:
```
Simulator (iPhone Xs)
true
```

Would also be the other way around when running on iPad and checking for `Device.iPhoneX.isPad`.

**Comment by dennisweissmann** [comment]
Woah that’s a great test case! Thanks for catching that (and sorry for the issue, of course)!

IIRC someone introduced the last or check to be compatible with future releases of phones without updating DeviceKit ...

I’ll think about a better solution for this!

**Comment by Zandor300** [comment]
Could be fixed like this:
```swift
UIDevice.current.userInterfaceIdiom == .phone && isCurrent
```
