### ISSUE TITLE
Getting values like device name uses UIDevice.current

### ISSUE THREAD

**Issue by Zandor300** [devicekit/DeviceKit#167]
I personally find it weird behaviour that it will return the current device name when executing the following code:

```swift
Device.iPhoneXs.name
```
Would return `Zandor's iPhone` even though I'm kind of referencing a different device.

I think putting a `fatalError(...)` or returning nil would be a more logical behaviour. `fatalError(...)` would notify the developer of incorrect behaviour immediately.

---

Another solution could be to check if we are referencing the current device:
```swift
Device().name
```

and if not, do something like described here: https://www.hackingwithswift.com/example-code/language/how-to-add-warnings-and-errors-to-your-code-using-warning-and-error

```swift
#error("Can't get the name of a different device from the current one.")
```

This would produce an error at compilation when my first example is being used.

---

Could be a possible change for 2.0.

**Comment by dennisweissmann** [comment]
Another great catch! I’m in favor of returning nil though, I think it’s a valid request to ask for a name of a device even though it might not be a real one. Returning nil makes sense to me.
