### ISSUE TITLE
Feature Request: Check if device supports ForceTouch/3DTouch

### ISSUE THREAD

**Issue by GabiGVeesto** [devicekit/DeviceKit#182]
Following are the devices on which Force Touch or 3D Touch technology is featured: 

### macOS (Force Touch)
- MacBook (Retina)
- MacBook Pro (early 2015 and later)
- MacBook Air 2018

### macOS accessories (Force Touch)
- Magic Trackpad 2

### iOS (3D Touch)
- iPhone 6s
- iPhone 6s Plus
- iPhone 7
- iPhone 7 Plus
- iPhone 8
- iPhone 8 Plus
- iPhone X
- iPhone Xs
- iPhone Xs Max

### watchOS (Force Touch)
- All Apple Watches

**Comment by Zandor300** [comment]
@GabiGVeesto Whoah, that is a really cool idea! I think we will definitely implement this!

I've edited your original message for us for better readability.
