### ISSUE TITLE
Swift Package not working

### ISSUE THREAD

**Issue by ValentinFromSpace** [devicekit/DeviceKit#197]
Unable to install DeviceKit as Swift Package from Xcode.

<img width="729" alt="Swift Package Error" src="https://user-images.githubusercontent.com/36477338/63654730-a33cfa80-c77e-11e9-90ea-b51a43120ba7.png">

**Comment by vegidio** [comment]
Same here. I get the error:

```
The package dependency graph can not be resolved; unable find any available tag for the following requirements:
https://github.com/devicekit/DeviceKit — 2.0.0..<3.0.0
```

**Comment by Zandor300** [comment]
Can you post your SPM config, or part of it?

_We are personally not that familiar with SPM..._

**Comment by denisenepraunig** [comment]
Hi @ValentinFromSpace  and @vegidio! Today I've released a new CocoaPods version and also a new release 2.1.0 which should include some fixes for SPM made by other contributors - @Zandor300  and I are not familiar with SPM. Does this fix the problem?

**Comment by ValentinFromSpace** [comment]
Yes! Working seamlessly now. Beautiful theme by the way!

**Comment by Zandor300** [comment]
Okay, I will be closing this now then! 👍🏻

**Comment by denisenepraunig** [comment]
> Yes! Working seamlessly now. Beautiful theme by the way!

@ValentinFromSpace Oh thank you 😊- I've used and adapted the [Fairyfloss Theme](https://github.com/sailorhg/fairyfloss) 💜.
