### ISSUE TITLE
iPhone 11?

### ISSUE THREAD

**Issue by supermafete** [devicekit/DeviceKit#203]
Hi!

Is there a plan to support new iPhone 11 devices? They're about to appear and we need to adapt our apps :)

Thanks.

**Comment by denisenepraunig** [comment]
Hi @supermafete! Today I merged https://github.com/devicekit/DeviceKit/pull/200 from @Zandor300 and I will release a new Cocoapods version tomorrow! I will close the issuse tomorrow! 😊👍

**Comment by supermafete** [comment]
Great news! Thank you for your effort. :)

**Comment by denisenepraunig** [comment]
Hi @supermafete - the new Cocoapods version 2.2.0 has just been released, I've tested with Xcode 11, added the link to our Github repo inside ```Swift Packages --> Add Package Dependency``` and the simulators for iPhone 11, 11 Pro and 11 Pro Max and it worked as expected now 😊. I am closing this issue now, have fun with the new release!
