### ISSUE TITLE
Ver. 2.1.0, can not recognize simulator of iPhone 11 Pro

### ISSUE THREAD

**Issue by bd-jhunter** [devicekit/DeviceKit#204]
Hello, 

test in iPhone 11 Pro simulator, with DeviceKit 2.1.0, Device.current.isSimulator return false.

(lldb) po Device.current
▿ Simulator (iPhone12,3)
  ▿ simulator : iPhone12,3
    - unknown : "iPhone12,3"

(lldb) po Device.current.isSimulator
false

**Comment by denisenepraunig** [comment]
Hi @bd-jhunter! Yesterday I merged #200 from @Zandor300 and I will release a new Cocoapods version today! I will close the issue one the pod is ready. 😊👍

**Comment by bd-jhunter** [comment]
oh, my mistake. I at first thought ver 2.1.0 is the one including merge #200

**Comment by denisenepraunig** [comment]
No problem 😉. Cocoapods version 2.2.0 was just released. I've tested with Xcode 11, added the link to our Github repo inside ```Swift Packages --> Add Package Dependency``` and the simulators for iPhone 11, 11 Pro and 11 Pro Max inside the ```application:didFinishWithOptions``` and got outputs like this:

```Swift
print(Device.current)
print(Device.current.isSimulator)
...
>> Simulator (iPhone 11 Pro Max)
>> true
```

So I am closing this issue now, have fun with our latest release!
