### ISSUE TITLE
Provide a sanitized or safe device description

### ISSUE THREAD

**Issue by rzulkoski** [devicekit/DeviceKit#216]
Although it is more technically correct to describe the device as "iPhone Xʀ", if that value eventually makes its way to a database it can cause issues depending on the column type. It would be nice if there was also a "sanitizedDescription" or "safeDescription" that would not contain special characters (e.g.: "iPhone XR").

**Comment by xiaoweiFive** [comment]
thk

**Comment by xiaoweiFive** [comment]
👍 thk
