### ISSUE TITLE
Device ppi returns nil for iPhone 11

### ISSUE THREAD

**Issue by mwangimorris** [devicekit/DeviceKit#223]

**Comment by Zandor300** [comment]
Are you running the latest version of DeviceKit? Version 2.3.0?

**Comment by mwangimorris** [comment]
I'm using version 2.1. Still on version 4.2 of Swift

**Comment by Zandor300** [comment]
2.1 is already on Swift 5 but code is compatible with the 4.2 compiler apparently. 2.2 introduces iPhone 11 support and 2.3 introduces support for the iPad (7th generation). Can you try updating to 2.3?
