### ISSUE TITLE
iPhone SE (2nd gen)

### ISSUE THREAD

**Issue by andynadheer** [devicekit/DeviceKit#243]
Hi,

I'm unable to see the 2nd generation SE in the device list. Is it supported or is not yet added? I can only see iPhone SE

**Comment by a-elnajjar** [comment]
Hi @andynadheer the support if iPhone SE 2nd gen added available on v3.2.0

**Comment by andynadheer** [comment]
@a-elnajjar  I tried installing devicekit by cocoapods and manually and I can still not see the 2nd gen iPhone SE in the list :(
