### ISSUE TITLE
hasBiometricSensor with Catalyst always returns false

### ISSUE THREAD

**Issue by laszlo-major** [devicekit/DeviceKit#247]
It seems that currently Device.current.hasBiometricSensor always returns false in a Catalyst app. Is there an elegant way to catch all touchID macbooks or it will require adding all the models?

Cheers

**Comment by Zandor300** [comment]
It will require adding all models of all Macs to support this on macOS, natively or through Catalyst.

See https://github.com/devicekit/DeviceKit/issues/184
