### ISSUE TITLE
Xcode 12.0 Deployment target warning

### ISSUE THREAD

**Issue by marcheimendinger** [devicekit/DeviceKit#258]
Starting with Xcode 12.0, I get a deployment target warning: `The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99.`

Any idea how to silence or 'fix' this? This is the only dependency in my project doing that.

**Comment by Zandor300** [comment]
Can be solved by updating to DeviceKit v4.0.0 using your Package Manager.
