### ISSUE TITLE
Add the latest Apple released devices like iPhone 12, iPhone 12 mini, Apple Watch Series 6, Apple Watch SE, iPad Air & iPad 8th generation

### ISSUE THREAD

**Issue by AgileFlexAgency** [devicekit/DeviceKit#263]
Add the latest Apple released devices:

- iPhone 12
- iPhone 12 mini
- Apple Watch Series 6
- Apple Watch SE
- iPad Air 
- iPad 8th generation

**Comment by denisenepraunig** [comment]
Thanks. We are already working on it. See https://github.com/devicekit/DeviceKit/pull/262

**Comment by AgileFlexAgency** [comment]
Thank you for your answer @denisenepraunig  👏 We will track the #262 issue.

Great work @dennisweissmann @denisenepraunig @Zandor300

**Comment by Zandor300** [comment]
@AgileFlexAgency 
iPad (8th generation), Apple Watch Series 6 and Apple Watch SE are already available in the [latest released version 4.1.0](https://github.com/devicekit/DeviceKit/releases/tag/4.1.0).
