### ISSUE TITLE
allDevicesWithALidarSensor wrong values

### ISSUE THREAD

**Issue by Tulleb** [devicekit/DeviceKit#266]
`    /// All devices that have a LiDAR sensor.
    public static var allDevicesWithALidarSensor: [Device] {
      return [.iPadPro11Inch2, .iPadPro12Inch4]
    }`

Aren't iPhone12Pro & iPhone12ProMax Lidar capable of as well?

**Comment by denisenepraunig** [comment]
Good catch @Tulleb! We will look into this, thank you!
