### ISSUE TITLE
iPadAir4 screen ratio is not correct??

### ISSUE THREAD

**Issue by oTranAnhMinh** [devicekit/DeviceKit#267]
Hello,

It seems that the screen ratio of iPad Air 4th is not correct.
// case .iPadAir4: return (width: 3, height: 4)

Is it exactly the same as the iPad Pro 11, right?
case .iPadPro11Inch: return (width: 139, height: 199)

**Comment by Zandor300** [comment]
Oh my mistake...

After calculating it, the aspect ratio of iPad Air (4th generation) is 41 : 59. I will push a PR to fix it.
