### ISSUE TITLE
Module Stability

### ISSUE THREAD

**Issue by damacster** [devicekit/DeviceKit#281]
Will DeviceKit be adding support for Module Stability? This is as simple as adding the BUILD_LIBRARY_FOR_DISTRIBUTION=Yes setting.

**Comment by denisenepraunig** [comment]
That is an interesting point, haven't thought about it. I will investigate this. @Zandor300 what do you think?

**Comment by damacster** [comment]
My apologies, i was using an older version of DeviceKit and it appears this setting is already been added since then.
