### ISSUE TITLE
Device.generated.swfit don't exists when importing DeviceKit with Carthage

### ISSUE THREAD

**Issue by bigmouthstrks** [devicekit/DeviceKit#287]
Hi, I'm not quite sure if this issue belongs to library itself or I'm missing something because of my lack of experience, but I have a library which depends on Alamofire and DeviceKit.
Right now I'm trying to replace the importing method of those dependencies from CocoaPods to Carthage, so I ran
```
pod deintegrate
pod cache clean --all
rm Podfile.lock
rm Podfile
```
In order to remove CocoaPods from the project.
After that I did 
```
touch Cartfile

# Inside Cartfile:
github "Alamofire/Alamofire"
github "devicekit/DeviceKit"

carthage update --use-xcframeworks --platform-ios

# and finally drag both generated .xcframeworks into my project
```

For my surprise, some line of code which contained ` Device.current ` wasn't working anymore, because current was not found.

The thing I realised was that when I install DeviceKit using CocoaPods I get a file named Device.generated.swift which contains current attribute (the one that's missing).
<img width="937" alt="Captura de Pantalla 2021-09-15 a la(s) 22 29 08" src="https://user-images.githubusercontent.com/26700995/133534755-397dbe66-86a8-49a1-b032-1d0de6491579.png">

**Comment by AgileFlexAgency** [comment]
@bigmouthstrks We have the same issue building the latest DeviceKit for Swift 5. **Device.current compiling error.**

@denisenepraunig Any work around for the version 4.5 that can be used when building with Carthage?
<img width="1582" alt="Screenshot 2021-09-23 at 14 54 05" src="https://user-images.githubusercontent.com/16820840/134503056-0000ebd2-41ad-4c60-b8b1-b0801543ed0d.png">
<img width="1575" alt="Screenshot 2021-09-23 at 14 58 13" src="https://user-images.githubusercontent.com/16820840/134503068-e44bca2d-b3a0-4a7f-804a-a64766fedb59.png">

**Comment by Zandor300** [comment]
@AgileFlexAgency Could you try if my changes in PR https://github.com/devicekit/DeviceKit/pull/288 fix your issue?

**Comment by AgileFlexAgency** [comment]
Hello @Zandor300 Thanks for your reply. We are using the standard **Cartfile** using the Carthage.sh script for xCode 12.
The issue seems to be with the 0.38.0 Carthage version when building the DeviceKit framework. 

We have downgraded to Carthage 0.37.0 and it seems the issue has been fixed.

**Comment by bigmouthstrks** [comment]
@Zandor300 I'll check these days and I'll let you know. Thanks a lot.

**Comment by kevinstier** [comment]
Any update on this?
