### ISSUE TITLE
Add support for iPhone SE Gen 3 & iPad Air Gen 5

### ISSUE THREAD

**Issue by jminutaglio** [devicekit/DeviceKit#309]
New iPhone SE is 14, 6

New iPad Air is 13, 17

per Xcode RC Version 13.3 (13E113)

Would be great to get these added, I think the ship 3/18...

:)

TY in advance!

**Comment by finetuning-mg** [comment]
There should be two different codes for the new 5th gen iPad Air, one for the WiFi model and one for the WiFi+cellular model.
For example, 4th gen iPad Air can be "iPad13,1" and "iPad13,2".

**Comment by jminutaglio** [comment]
iPad13,17 is most likely Wifi; 13,18 most likely WiFi_Cellular.  Not 100% sure how to map those models in the simulator but that is the historical pattern...

**Comment by finetuning-mg** [comment]
According to several sources online, the new model codes should be:
"iPhone14,6" --> iPhone SE (3rd generation)
"iPad13,16" --> iPad Air (5th generation) Wi-Fi
"iPad13,17" --> iPad Air (5th generation) Wi-Fi + Cellular
