### ISSUE TITLE
Add Watch Series 7

### ISSUE THREAD

**Issue by daniellakehorn** [devicekit/DeviceKit#323]
**Could you please add Watch Series 7:**

Watch6,6 : Apple Watch Series 7 41mm case (GPS)
Watch6,7 : Apple Watch Series 7 45mm case (GPS)
Watch6,8 : Apple Watch Series 7 41mm case (GPS+Cellular)
Watch6,9 : Apple Watch Series 7 45mm case (GPS+Cellular)

Technical Specs: https://support.apple.com/kb/SP860

Thank you!

**Comment by jairhart** [comment]
It's already a ticket #306. But also need to add Series 8 and SE (2nd gen).

**Comment by cvdevmaster** [comment]
Apple Watch Ultra as well... because there will be different feature capabilities on it.
