### ISSUE TITLE
Old version is installed from CocoaPods

### ISSUE THREAD

**Issue by SergejLogis** [devicekit/DeviceKit#331]
Both 
`pod 'DeviceKit', '~> 4.0'` and
`pod 'DeviceKit'`
install the older 4.6.1 version.

The only way to install the latest 4.7.0 version is to specify `git` directly:
`pod 'DeviceKit', :git => 'https://github.com/devicekit/DeviceKit'`

**Comment by Zandor300** [comment]
@SergejLogis If you run `pod install --repo-update`, will it install 4.8.0 then? (4.8.0 is latest version now)

**Comment by SergejLogis** [comment]
> @SergejLogis If you run `pod install --repo-update`, will it install 4.8.0 then? (4.8.0 is latest version now)

Thanks, @Zandor300! Now it works 🥳 

**P.S.** I needed to follow the steps in [StackOverflow](https://stackoverflow.com/a/71819482/944839) to make it work. Some time ago something happened to CocoaPods, and `pod update` or `pod install --repo-update` stopped from working (throws exception). But StackOverflow solution helped 🤓
