### ISSUE TITLE
No longer compiles on visionOS

### ISSUE THREAD

**Issue by chrisvasselli** [devicekit/DeviceKit#370]
Recent versions of the visionOS beta have changed the behavior of `#if os(iOS)` to no longer return true on visionOS. Previous versions of the visionOS beta returned true to this. With this change, DeviceKit is once again not compiling on visionOS.

**Comment by MashfiqueA** [comment]
Support for visionOS would be a great enhancement. Eagerly awaiting this update!

**Comment by gabors** [comment]
@Zandor300 Please add enough support so we can compile on visionOS for now, actual features can come later.
