### ISSUE TITLE
iPhone XR

### ISSUE THREAD

**Issue by lipopli** [devicekit/DeviceKit#395]
case .iPhoneXR: return "iPhone Xʀ"  这个“ʀ”的字符有问题，应该是"iPhone XR" ，导致我的网络请求header 里认不出来，网络请求错误

**Comment by Zandor300** [comment]
Rough Google Translate, please communicate in English:

> case .iPhoneXR: return "iPhone Xʀ" There is something wrong with the "ʀ" character. It should be "iPhone

This is done on purpose. If you don't like this behavior, the `.safeDescription` property is available where these special characters aren't used.

**Comment by lipopli** [comment]
Thanks, use  Device.current.safeDescription solve it！
