### ISSUE TITLE
Describing use of required reason API

### ISSUE THREAD

**Issue by Gregorian-st** [devicekit/DeviceKit#400]
According to Apple, "starting May 1, 2024, when you upload a new app or app update, you must include a NSPrivacyAccessedAPITypes array in your app’s privacy manifest to provide approved reasons for these APIs used by your app’s code"
As stated here https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api
For each category of required reason API that your app or third-party SDK uses, add a dictionary to the NSPrivacyAccessedAPITypes array in your app or third-party SDK’s privacy manifest file that reports the reasons your app uses the API category. If you use the API in your third-party SDK’s code, then you need to report the API in your third-party SDK’s privacy manifest file. Your third-party SDK can’t rely on the privacy manifest files for apps that link the third-party SDK, or those of other third-party SDKs the app links, to report your third-party SDK’s use of required reasons API.

Could you include PrivacyInfo.xcprivacy file into the package?

**Comment by Gregorian-st** [comment]
More info about it here https://developer.apple.com/videos/play/wwdc2023/10060

**Comment by herrernst** [comment]
It's already included, doesn't it work for you? https://github.com/devicekit/DeviceKit/blob/master/Source/PrivacyInfo.xcprivacy

**Comment by Gregorian-st** [comment]
<img width="1558" alt="DeviceKit" src="https://github.com/devicekit/DeviceKit/assets/66716883/79047ec0-4ad4-40e3-863f-c497fa178776">
No, it doesn't. May be because the Target Membership for this file is no set to DeviceKit. Also Apple requested to provide the reasons for using API category NSPrivacyAccessedAPICategoryFileTimestamp. I don't use file access in my project, so I suspect DeviceKit Package is using it.

**Comment by didix21** [comment]
I have the same problem when I generate a xcframework using xcodeproj. As @Gregorian-st the problem seems PrivacyInfo.xcprivacy isn't added as a target on DeviceKit.

**Comment by Zandor300** [comment]
Fixed by https://github.com/devicekit/DeviceKit/pull/397 released just now in version 5.2.3
