### ISSUE TITLE
Add Privacy Manifest

### ISSUE THREAD

**Issue by sagarthecoder** [devicekit/DeviceKit#404]
Apple says "**Starting May 1, 2024: You'll need to include approved reasons for the listed APIs used by your app's code to upload a new or updated app to App Store Connect.**"

Please add privacy policy otherwise we couldn't use this library.

**Comment by mathaeus** [comment]
@Zandor300 is this something you can provide? I guess without it for most people it means looking for an alternative to `DeviceKit` :)

**Comment by Zandor300** [comment]
Fixed by https://github.com/devicekit/DeviceKit/pull/397 released just now in version 5.2.3

Just in time before Apple starts enforcing the change :)

**Comment by acrabb** [comment]
thanks!
