### ISSUE TITLE
Multiple commands produce PrivacyInfo.xcprivacy

### ISSUE THREAD

**Issue by poxxhub** [devicekit/DeviceKit#405]
In Podspec, the privacy manifest should be placed in the resource_bundles attribute, not in the resources.
Reference: "[Multiple commands produce PrivacyInfo.xcprivacy #1408"](https://github.com/CocoaLumberjack/CocoaLumberjack/issues/1408#:~:text=Multiple%20commands%20produce%20PrivacyInfo.xcprivacy%20%231408)
https://github.com/getsentry/sentry-react-native/issues/3599

**Comment by Zandor300** [comment]
Fixed by https://github.com/devicekit/DeviceKit/pull/397 released just now in version 5.2.3
