### ISSUE TITLE
iPhone 16 support

### ISSUE THREAD

**Issue by harikrishnank333** [devicekit/DeviceKit#421]
Please let me know when can we expect an update which supports iPhone 16 series

**Comment by gabors** [comment]
Also would like to know

**Comment by Quailcreek** [comment]
It's been 5 hours since version 5.5.0 was supposedly released. It still is not available to update in my app either. I'm not sure how long it normally takes to get it released.
I noticed that in the README file on github the pod callout is still V5.4.0. Not sure if that's the problem or not.

**Comment by gabors** [comment]
The new version was't tagged and released yet, maybe the dev is still testing something

**Comment by Zandor300** [comment]
v5.5.0 was released today with iPhone 16 series support.
